In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
Dataset = {
    'Employee ID': np.arange(1, 21),
    'Name': [f'Employee_{i}' for i in range(1, 21)],
    'Department': np.random.choice(['HR', 'Engineering', 'Marketing', 'Sales', 'Finance'], 20),
    'Age': np.random.randint(22, 60, 20),
    'Salary': np.random.randint(40000, 120000, 20)
}
df = pd.DataFrame(Dataset)

In [3]:
df.head()

   Employee ID        Name   Department  Age  Salary
0            1  Employee_1  Engineering   28   58014
1            2  Employee_2  Engineering   40   45661
2            3  Employee_3      Finance   46  117039
3            4  Employee_4  Engineering   43   85863
4            5  Employee_5           HR   45   69691

In [4]:
df.tail()

    Employee ID         Name   Department  Age  Salary
15           16  Employee_16        Sales   37   96766
16           17  Employee_17      Finance   22   81578
17           18  Employee_18    Marketing   43  105358
18           19  Employee_19  Engineering   57   89179
19           20  Employee_20      Finance   25   69103

In [5]:
display(df.columns.tolist())

['Employee ID', 'Name', 'Department', 'Age', 'Salary']

In [6]:
display(df.dtypes)

Employee ID     int64
Name           object
Department     object
Age             int64
Salary          int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  20 non-null     int64
 1   Name         20 non-null     object
 2   Department   20 non-null     object
 3   Age          20 non-null     int64
 4   Salary       20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 932.0+ bytes

In [8]:
df.describe()

       Employee ID        Age         Salary
count     20.00000  20.000000      20.000000
mean      10.50000  37.600000   81687.650000
std        5.91608  11.320219   23031.955013
min        1.00000  22.000000   43824.000000
25%        5.75000  27.250000   66330.750000
50%       10.50000  36.500000   84489.500000
75%       15.25000  45.250000   97110.250000
max       20.00000  57.000000  117039.000000

In [12]:
df.isnull().sum()

Employee ID    0
Name           0
Department     0
Age            0
Salary         0
dtype: int64

In [13]:
(df.isnull().sum() / len(df)) * 100

Employee ID    0.0
Name           0.0
Department     0.0
Age            0.0
Salary         0.0
dtype: float64